# Generated by Django 2.1.7 on 2020-01-16 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('description', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Downloads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.URLField(max_length=512)),
                ('version', models.DecimalField(decimal_places=3, max_digits=3)),
                ('release_date', models.DateTimeField(null=True)),
                ('release_notes', models.CharField(max_length=200)),
                ('is_available_for_download', models.BooleanField(default=False)),
                ('application', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='downloads.Application')),
            ],
        ),
    ]
