# Generated by Django 2.1.7 on 2020-01-10 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoodleListing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_public', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('subject', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Human',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('is_buyer', models.BooleanField(default=False)),
                ('is_seller', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=30)),
                ('zip_code', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='doodle',
            name='birthdate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='doodle',
            name='is_for_sale',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='doodle',
            name='picture',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='doodlelisting',
            name='doodle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='directory.Doodle'),
        ),
        migrations.AddField(
            model_name='doodle',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='directory.Human'),
        ),
    ]
