# Generated by Django 2.1.7 on 2020-01-10 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0002_auto_20200110_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='doodlelisting',
            name='cost',
            field=models.FloatField(default=2000),
        ),
    ]
